/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package conexao;

public enum Metodos {
    LOGOUT,INSERIR,LISTAR,LISTAR2,ALTERAR,EXCLUIR,VALIDAR,VALIDAR2,VALIDARNOME,LISTARVENCIDOS,
    LISTARVENCENDO,LISTARADIMPLENTE,GERARRELATORIO,GERARRELATORIO2,INATIVAR,CANCELAR,
    ATIVAR, VALIDAREMAIL,NOVASENHA,FILTRAR,RECIBO,EMAILCOMPROVANTE,RECUPERARCODIGO,
    VERIFICARNOMEALUNO,ENVIARPDFPOREMAIL,ALTERARSENHA,EXCLUIRFOTO,TESTE,BUSCAR_ALUNOS,
    LISTARMENSALIDADESPORALUNO,INSERIR2,DATATABLE,CONTADORMENSALIDADE,CONTDIA,CONTMES,
    CONTANO;
}
